export const RESET_ROUNDS_STORE = "RESET_ROUNDS_STORE";
export const RESET_ROUND_STORE = "RESET_ROUND_STORE";
export const RESET_RAYCASTER_STORE = "RESET_RAYCASTER_STORE";
export const RESET_LOADER_STORE = "RESET_LOADER_STORE";
export const RESET_EDITING_MODE_STORE = "RESET_EDITING_MODE_STORE";
export const RESET_CAMERA_STORE = "RESET_CAMERA_STORE";
export const RESET_COLLABORATION_STORE = "RESET_COLLABORATION_STORE";
export const RESET_LAST_EDITOR = "RESET_LAST_EDITOR ";

export const TOGGLE_LOADER = "TOGGLE_LOADER";
export const TOGGLE_RAYCASTER = "TOGGLE_RAYCASTER";
export const SET_CAMERA = "SET_CAMERA";
export const SET_EDITING_MODE = "SET_EDITING_MODE";

export const SET_ROUNDS = "SET_ROUNDS";
export const ADD_ROUND = "ADD_ROUND";
export const REMOVE_ROUND = "REMOVE_ROUND";
export const UPDATE_ROUND = "UPDATE_ROUND";

export const SET_ROUND_DATA = "SET_ROUND_DATA";

export const TOGGLE_STEP = "TOGGLE_STEP";
export const SET_STEP_VELOCITY = "SET_STEP_VELOCITY";
export const SET_STEP_PROBABILITY = "SET_STEP_PROBABILITY";
export const SET_STEP_NOTE = "SET_STEP_NOTE";

export const TOGGLE_LAYER = "TOGGLE_LAYER";
export const SET_LAYER_NAME = "SET_LAYER_NAME";
export const UPDATE_LAYER_INSTRUMENT = "UPDATE_LAYER_INSTRUMENT";
export const ADD_LAYER_STEP = "ADD_LAYER_STEP";
export const REMOVE_LAYER_STEP = "REMOVE_LAYER_STEP";
export const SET_LAYER_STEPS = "SET_LAYER_STEPS";

export const ADD_ROUND_LAYER = "ADD_ROUND_LAYER";
export const ADD_ROUND_LAYERS = "ADD_ROUND_LAYERS";
export const REMOVE_ROUND_LAYER = "REMOVE_ROUND_LAYER";
export const SET_ROUND_NAME = "SET_ROUND_NAME";
export const SET_ROUND_BPM = "SET_ROUND_BPM";
export const SET_ROUND_ID = "SET_ROUND_ID";

export const SET_USER = "SET_USER";
export const CLEAR_USER = "CLEAR_USER";

export const SET_COLLABORATION = "SET_COLLABORATION";

export const SET_CONTRIBUTORS_POSITIONS = "SET_CONTRIBUTORS_POSITIONS";
export const SET_LAYERS_POSITIONS = "SET_LAYERS_POSITIONS";
export const SET_STEPS_POSITIONS = "SET_STEPS_POSITIONS";
export const SET_LAYER_CONTROLS_POSITION = "SET_LAYER_CONTROLS_POSITION";
export const SET_ROUND_INFO_POSITION = "SET_ROUND_INFO_POSIT";